// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/coze-dev/coze-loop/backend/modules/foundation/infra/repo/mysql/gorm_gen/model"
)

func newLoginAudit(db *gorm.DB, opts ...gen.DOOption) loginAudit {
	_loginAudit := loginAudit{}

	_loginAudit.loginAuditDo.UseDB(db, opts...)
	_loginAudit.loginAuditDo.UseModel(&model.LoginAudit{})

	tableName := _loginAudit.loginAuditDo.TableName()
	_loginAudit.ALL = field.NewAsterisk(tableName)
	_loginAudit.ID = field.NewInt64(tableName, "id")
	_loginAudit.UserID = field.NewInt64(tableName, "user_id")
	_loginAudit.LoginType = field.NewInt8(tableName, "login_type")
	_loginAudit.Provider = field.NewString(tableName, "provider")
	_loginAudit.IP = field.NewString(tableName, "ip")
	_loginAudit.UserAgent = field.NewString(tableName, "user_agent")
	_loginAudit.Success = field.NewInt8(tableName, "success")
	_loginAudit.FailReason = field.NewString(tableName, "fail_reason")
	_loginAudit.CreatedAt = field.NewTime(tableName, "created_at")

	_loginAudit.fillFieldMap()

	return _loginAudit
}

// loginAudit login_audit table
type loginAudit struct {
	loginAuditDo loginAuditDo

	ALL        field.Asterisk
	ID         field.Int64  // Primary Key ID
	UserID     field.Int64  // User ID
	LoginType  field.Int8   // Login Type (1=password, 2=Gitee OAuth)
	Provider   field.String // OAuth Provider
	IP         field.String // IP Address
	UserAgent  field.String // User Agent
	Success    field.Int8   // Success (1=success, 0=fail)
	FailReason field.String // Failure Reason
	CreatedAt  field.Time   // Created Time

	fieldMap map[string]field.Expr
}

func (l loginAudit) Table(newTableName string) *loginAudit {
	l.loginAuditDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l loginAudit) As(alias string) *loginAudit {
	l.loginAuditDo.DO = *(l.loginAuditDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *loginAudit) updateTableName(table string) *loginAudit {
	l.ALL = field.NewAsterisk(table)
	l.ID = field.NewInt64(table, "id")
	l.UserID = field.NewInt64(table, "user_id")
	l.LoginType = field.NewInt8(table, "login_type")
	l.Provider = field.NewString(table, "provider")
	l.IP = field.NewString(table, "ip")
	l.UserAgent = field.NewString(table, "user_agent")
	l.Success = field.NewInt8(table, "success")
	l.FailReason = field.NewString(table, "fail_reason")
	l.CreatedAt = field.NewTime(table, "created_at")

	l.fillFieldMap()

	return l
}

func (l *loginAudit) WithContext(ctx context.Context) *loginAuditDo { return l.loginAuditDo.WithContext(ctx) }

func (l loginAudit) TableName() string { return l.loginAuditDo.TableName() }

func (l loginAudit) Alias() string { return l.loginAuditDo.Alias() }

func (l loginAudit) Columns(cols ...field.Expr) gen.Columns { return l.loginAuditDo.Columns(cols...) }

func (l *loginAudit) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *loginAudit) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 10)
	l.fieldMap["id"] = l.ID
	l.fieldMap["user_id"] = l.UserID
	l.fieldMap["login_type"] = l.LoginType
	l.fieldMap["provider"] = l.Provider
	l.fieldMap["ip"] = l.IP
	l.fieldMap["user_agent"] = l.UserAgent
	l.fieldMap["success"] = l.Success
	l.fieldMap["fail_reason"] = l.FailReason
	l.fieldMap["created_at"] = l.CreatedAt
}

func (l loginAudit) clone(db *gorm.DB) loginAudit {
	l.loginAuditDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l loginAudit) replaceDB(db *gorm.DB) loginAudit {
	l.loginAuditDo.ReplaceDB(db)
	return l
}

type loginAuditDo struct{ gen.DO }

func (l loginAuditDo) Debug() *loginAuditDo {
	return l.withDO(l.DO.Debug())
}

func (l loginAuditDo) WithContext(ctx context.Context) *loginAuditDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l loginAuditDo) ReadDB() *loginAuditDo {
	return l.Clauses(dbresolver.Read)
}

func (l loginAuditDo) WriteDB() *loginAuditDo {
	return l.Clauses(dbresolver.Write)
}

func (l loginAuditDo) Session(config *gorm.Session) *loginAuditDo {
	return l.withDO(l.DO.Session(config))
}

func (l loginAuditDo) Clauses(conds ...clause.Expression) *loginAuditDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l loginAuditDo) Returning(value interface{}, columns ...string) *loginAuditDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l loginAuditDo) Not(conds ...gen.Condition) *loginAuditDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l loginAuditDo) Or(conds ...gen.Condition) *loginAuditDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l loginAuditDo) Select(conds ...field.Expr) *loginAuditDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l loginAuditDo) Where(conds ...gen.Condition) *loginAuditDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l loginAuditDo) Order(conds ...field.Expr) *loginAuditDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l loginAuditDo) Distinct(cols ...field.Expr) *loginAuditDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l loginAuditDo) Omit(cols ...field.Expr) *loginAuditDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l loginAuditDo) Join(table schema.Tabler, on ...field.Expr) *loginAuditDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l loginAuditDo) LeftJoin(table schema.Tabler, on ...field.Expr) *loginAuditDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l loginAuditDo) RightJoin(table schema.Tabler, on ...field.Expr) *loginAuditDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l loginAuditDo) Group(cols ...field.Expr) *loginAuditDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l loginAuditDo) Having(conds ...gen.Condition) *loginAuditDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l loginAuditDo) Limit(limit int) *loginAuditDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l loginAuditDo) Offset(offset int) *loginAuditDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l loginAuditDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *loginAuditDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l loginAuditDo) Unscoped() *loginAuditDo {
	return l.withDO(l.DO.Unscoped())
}

func (l loginAuditDo) Create(values ...*model.LoginAudit) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l loginAuditDo) CreateInBatches(values []*model.LoginAudit, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l loginAuditDo) Save(values ...*model.LoginAudit) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l loginAuditDo) First() (*model.LoginAudit, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginAudit), nil
	}
}

func (l loginAuditDo) Take() (*model.LoginAudit, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginAudit), nil
	}
}

func (l loginAuditDo) Last() (*model.LoginAudit, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginAudit), nil
	}
}

func (l loginAuditDo) Find() ([]*model.LoginAudit, error) {
	result, err := l.DO.Find()
	return result.([]*model.LoginAudit), err
}

func (l loginAuditDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.LoginAudit, err error) {
	buf := make([]*model.LoginAudit, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l loginAuditDo) FindInBatches(result *[]*model.LoginAudit, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l loginAuditDo) Attrs(attrs ...field.AssignExpr) *loginAuditDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l loginAuditDo) Assign(attrs ...field.AssignExpr) *loginAuditDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l loginAuditDo) Joins(fields ...field.RelationField) *loginAuditDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l loginAuditDo) Preload(fields ...field.RelationField) *loginAuditDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l loginAuditDo) FirstOrInit() (*model.LoginAudit, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginAudit), nil
	}
}

func (l loginAuditDo) FirstOrCreate() (*model.LoginAudit, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.LoginAudit), nil
	}
}

func (l loginAuditDo) FindByPage(offset int, limit int) (result []*model.LoginAudit, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l loginAuditDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l loginAuditDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l loginAuditDo) Delete(models ...*model.LoginAudit) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *loginAuditDo) withDO(do gen.Dao) *loginAuditDo {
	l.DO = *do.(*gen.DO)
	return l
}
